# Sentiment Classification 
### (Question 3 is done first and 2 is done after that )


# 1.Loading the dataset

In [123]:
from keras.datasets import imdb

vocab_size = 10000 #vocab size

(x_train, y_train), (x_test,y_test) = imdb.load_data(num_words=vocab_size) # vocab_size is no.of words to consider from the dataset, ordering based on frequency.

In [124]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 300  #number of word used from each review

### From the documentation for Keras IMBD Dataset, the data is encoded along with 3 important points
> 1. The encoding 0 is used for pad words  
> 2. The encoding 1 is used to mark the begining of a sentence
> 3. The encoding 2 is used to mark words which are outside if the vocabulary of 10000, in this case

# 3.Get the word index and then Create a key-value pair for word and word_id
(15 points)

### Loading entire dataset to create Key-Value pair

In [125]:
(x,y)=imdb.load_data(num_words=vocab_size)

In [126]:
word_index=imdb.get_word_index()

In [127]:
word_index

{'fawn': 34701,
 'tsukino': 52006,
 'nunnery': 52007,
 'sonja': 16816,
 'vani': 63951,
 'woods': 1408,
 'spiders': 16115,
 'hanging': 2345,
 'woody': 2289,
 'trawling': 52008,
 "hold's": 52009,
 'comically': 11307,
 'localized': 40830,
 'disobeying': 30568,
 "'royale": 52010,
 "harpo's": 40831,
 'canet': 52011,
 'aileen': 19313,
 'acurately': 52012,
 "diplomat's": 52013,
 'rickman': 25242,
 'arranged': 6746,
 'rumbustious': 52014,
 'familiarness': 52015,
 "spider'": 52016,
 'hahahah': 68804,
 "wood'": 52017,
 'transvestism': 40833,
 "hangin'": 34702,
 'bringing': 2338,
 'seamier': 40834,
 'wooded': 34703,
 'bravora': 52018,
 'grueling': 16817,
 'wooden': 1636,
 'wednesday': 16818,
 "'prix": 52019,
 'altagracia': 34704,
 'circuitry': 52020,
 'crotch': 11585,
 'busybody': 57766,
 "tart'n'tangy": 52021,
 'burgade': 14129,
 'thrace': 52023,
 "tom's": 11038,
 'snuggles': 52025,
 'francesco': 29114,
 'complainers': 52027,
 'templarios': 52125,
 '272': 40835,
 '273': 52028,
 'zaniacs': 52130,

### Testing the Key-Value Pair to check if the enodings match with Dataset

In [128]:
id_word={v:u for u,v in word_index.items()}

In [129]:
for i in x[0][0]:
    print(id_word[i])

the
as
you
with
out
themselves
powerful
lets
loves
their
becomes
reaching
had
journalist
of
lot
from
anyone
to
have
after
out
atmosphere
never
more
room
and
it
so
heart
shows
to
years
of
every
never
going
and
help
moments
or
of
every
chest
visual
movie
except
her
was
several
of
enough
more
with
is
now
current
film
as
you
of
mine
potentially
unfortunately
of
you
than
him
that
with
out
themselves
her
get
for
was
camp
of
you
movie
sometimes
movie
that
with
scary
but
and
to
story
wonderful
that
in
seeing
in
character
to
of
70s
musicians
with
heart
had
shadows
they
of
here
that
with
her
serious
to
have
does
when
from
why
what
have
critics
they
is
you
that
isn't
one
will
very
to
as
itself
with
other
and
in
of
seen
over
landed
for
anyone
of
and
br
show's
to
whether
from
than
out
themselves
history
he
name
half
some
br
of
and
odd
was
two
most
of
mean
for
1
any
an
boat
she
he
should
is
thought
frog
but
of
script
you
not
while
history
he
heart
to
real
at
barrel
but
when
from
one
bit
then
have
tw

### Clearly the sentence doesn't make sense. Hence there is some problem with the encoding


In [130]:
print(id_word[0],id_word[1],id_word[2],id_word[3])

KeyError: 0

### The Pad Words, Start Words, Unknown Words, and Unused words are not encoded properly in the Key_Value Pair. Hence it has to be manually added

In [131]:
id_word={u:v+3 for u,v in word_index.items()}
id_word['<PAD/>']=0
id_word['<START/>']=1
id_word['<UNUSED/>']=2
id_word['<UNKNOWN/>']=3

In [132]:
id_word={v:u for u,v in id_word.items()}

In [133]:
sent=[]
for i in x[0][0]:
    sent.append(id_to_word[i])
print(sent)

['<START/>', 'this', 'film', 'was', 'just', 'brilliant', 'casting', 'location', 'scenery', 'story', 'direction', "everyone's", 'really', 'suited', 'the', 'part', 'they', 'played', 'and', 'you', 'could', 'just', 'imagine', 'being', 'there', 'robert', '<UNUSED/>', 'is', 'an', 'amazing', 'actor', 'and', 'now', 'the', 'same', 'being', 'director', '<UNUSED/>', 'father', 'came', 'from', 'the', 'same', 'scottish', 'island', 'as', 'myself', 'so', 'i', 'loved', 'the', 'fact', 'there', 'was', 'a', 'real', 'connection', 'with', 'this', 'film', 'the', 'witty', 'remarks', 'throughout', 'the', 'film', 'were', 'great', 'it', 'was', 'just', 'brilliant', 'so', 'much', 'that', 'i', 'bought', 'the', 'film', 'as', 'soon', 'as', 'it', 'was', 'released', 'for', '<UNUSED/>', 'and', 'would', 'recommend', 'it', 'to', 'everyone', 'to', 'watch', 'and', 'the', 'fly', 'fishing', 'was', 'amazing', 'really', 'cried', 'at', 'the', 'end', 'it', 'was', 'so', 'sad', 'and', 'you', 'know', 'what', 'they', 'say', 'if', 'yo

### Now the sentence makes more sense. And Hence we have the proper encoding

# 2.Import the labels (train and test) 
(5 points)

## Train test split

In [134]:
#load dataset as a list of ints
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test =  pad_sequences(x_test, maxlen=maxlen)

In [135]:
from tensorflow.keras.utils import to_categorical

y_train=to_categorical(y_train,num_classes=2)
y_test=to_categorical(y_test,num_classes=2)

# 4.Build a Sequential Model using Keras for the Sentiment Classification task
(15 points)

## Build Keras Embedding Layer Model
We can think of the Embedding layer as a dicionary that maps a index assigned to a word to a word vector. This layer is very flexible and can be used in a few ways:

* The embedding layer can be used at the start of a larger deep learning model. 
* Also we could load pre-train word embeddings into the embedding layer when we create our model.
* Use the embedding layer to train our own word2vec models.

The keras embedding layer doesn't require us to onehot encode our words, instead we have to give each word a unqiue intger number as an id. For the imdb dataset we've loaded this has already been done, but if this wasn't the case we could use sklearn [LabelEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html).

In [146]:
max_len = 300
from tensorflow.keras.models import Model
from tensorflow.keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional, Input
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence

In [159]:
model = Sequential()
model.add(Embedding(vocab_size, 32, input_length=maxlen))
model.add(Flatten())
model.add(Dense(250, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 300, 32)           320000    
_________________________________________________________________
flatten_3 (Flatten)          (None, 9600)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 250)               2400250   
_________________________________________________________________
dense_6 (Dense)              (None, 50)                12550     
_________________________________________________________________
dense_7 (Dense)              (None, 2)                 102       
Total params: 2,732,902
Trainable params: 2,732,902
Non-trainable params: 0
_________________________________________________________________
None


In [160]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=2, batch_size=128, verbose=2)
scores = model.evaluate(x_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

/home/sandheepgopinath/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 25000 samples, validate on 25000 samples
Epoch 1/2
 - 7s - loss: 0.4559 - accuracy: 0.7513 - val_loss: 0.2936 - val_accuracy: 0.8751
Epoch 2/2
 - 7s - loss: 0.1444 - accuracy: 0.9480 - val_loss: 0.3442 - val_accuracy: 0.8620
Accuracy: 86.20%


# 5. Report accuracy for the model 
(5 Marks)

In [162]:
model.evaluate(x_test,y_test)

25000/25000 [==============================] - 2s 86us/step


[0.3442105972480774, 0.8619599938392639]

In [175]:
import numpy as np
np.round(model.predict(x_test))

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [231]:
sent=[]
for i in x_test[0]:
    sent.append(id_to_word[i])
print(sent)

['<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>',

In [232]:
y_test[0]

array([1., 0.], dtype=float32)

### We have created a sentiment classification model with 86% Accuracy

# 6. Retrive the output of each layer in keras for a given single test sample from the trained model you built
(5 Points)

### Output of First Layer

In [198]:
from keras.models import Model
models=Model(inputs=model.input,outputs=model.get_layer('embedding_3').output)

In [209]:
o1=models.predict(x_test[0].reshape(1,300))

In [210]:
o1.shape

(1, 300, 32)

### As expected the output of the first layer is of size 1,300,32

In [211]:
o1

array([[[ 0.00813   ,  0.00094273, -0.00665485, ...,  0.00915959,
          0.00645069,  0.00817401],
        [ 0.00813   ,  0.00094273, -0.00665485, ...,  0.00915959,
          0.00645069,  0.00817401],
        [ 0.00813   ,  0.00094273, -0.00665485, ...,  0.00915959,
          0.00645069,  0.00817401],
        ...,
        [-0.031931  , -0.02404551, -0.00283176, ...,  0.04132502,
         -0.04615477, -0.0039544 ],
        [ 0.01279813,  0.01607789, -0.06720804, ..., -0.02534747,
         -0.00830697, -0.03441942],
        [ 0.01772439, -0.0252034 , -0.01350909, ..., -0.02957739,
         -0.03138706,  0.05071835]]], dtype=float32)

In [213]:
model2=Model(inputs=model.input,outputs=model.get_layer('flatten_3').output)
o2=model2.predict(x_test[0].reshape(1,300))

In [214]:
o2.shape

(1, 9600)

In [215]:
o2

array([[ 0.00813   ,  0.00094273, -0.00665485, ..., -0.02957739,
        -0.03138706,  0.05071835]], dtype=float32)

### We have a flattened 9600x1 output from second layer after the flatting has been applied.
#### In the following layers we have Fully Connected Layers


In [219]:
model3=Model(inputs=model.input,outputs=model.get_layer('dense_5').output)
o3=model3.predict(x_test[0].reshape(1,300))

In [220]:
o3.shape 

(1, 250)

In [221]:
o3

array([[0.        , 0.        , 0.14111547, 0.        , 0.        ,
        0.        , 0.19540031, 0.07427282, 0.        , 0.        ,
        0.02589631, 0.        , 0.18722092, 0.42787516, 0.        ,
        0.        , 0.2352777 , 0.        , 0.19809937, 0.        ,
        0.        , 0.05805032, 0.        , 0.03171595, 0.09026735,
        0.        , 0.        , 0.08571997, 0.        , 0.        ,
        0.        , 0.        , 0.11480962, 0.        , 0.        ,
        0.        , 0.31446147, 0.25873536, 0.08357201, 0.        ,
        0.47632796, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.17734888, 0.        , 0.46339345, 0.04487868, 0.        ,
        0.01748249, 0.18190584, 0.24897915, 0.        , 0.09418121,
        0.04888644, 0.05102567, 0.        , 0.01515339, 0.        ,
        0.        , 0.        , 0.04373129, 0.        , 0.        ,
        0.0040416 , 0.20082155, 0.17949012, 0.29

### We have a layer with 250 output neurons which will further reduce to 50 in next layer

In [222]:
model4=Model(inputs=model.input,outputs=model.get_layer('dense_6').output)
o4=model4.predict(x_test[0].reshape(1,300))

In [223]:
o4.shape

(1, 50)

In [224]:
o4

array([[0.        , 0.        , 0.5029766 , 0.9663856 , 0.        ,
        0.        , 0.88672435, 1.146144  , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.4394068 ,
        0.        , 0.45498055, 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.064084  , 2.2073271 , 0.        ,
        1.4390311 , 0.44572046, 0.        , 1.8867363 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.0320477 , 0.9389712 , 1.6238228 , 1.7407179 , 0.        ,
        0.78982234, 0.        , 0.        , 1.1589043 , 0.        ,
        0.        , 1.1530837 , 0.        , 1.9048778 , 0.        ]],
      dtype=float32)

### And the final layer has a classification output with 2 stages

In [225]:
model5=Model(inputs=model.input,outputs=model.get_layer('dense_7').output)
o5=model5.predict(x_test[0].reshape(1,300))

In [226]:
o5.shape

(1, 2)

In [227]:
o5

array([[0.97204226, 0.02691413]], dtype=float32)

## The model indicates that the review had a negative sentiment associated with it which is quite evident from the below review

In [233]:
sent=[]
for i in x_test[0]:
    sent.append(id_to_word[i])
print(sent)

['<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>', '<PAD/>',